@startuml
interface ControlRemoto {
    +sincronizar()
}

abstract class Dispositivo {
    - String nombre
    - boolean estado
    # Dispositivo(String nombre)
    # encender()
    + apagar()
    + mostrarEstado()
}

class Televisor extends Dispositivo implements ControlRemoto {
    + encender()
    + sincronizar()
}

class ParlanteInteligente extends Dispositivo {
    + encender()
}

class AireAcondicionado extends Dispositivo implements ControlRemoto {
    + encender()
    + sincronizar()
}

class AppGestionDispositivos {
    + main(String[] args)
}

Dispositivo <|-- Televisor
Dispositivo <|-- ParlanteInteligente
Dispositivo <|-- AireAcondicionado

ControlRemoto <|.. Televisor
ControlRemoto <|.. AireAcondicionado

AppGestionDispositivos ..> Dispositivo : "listaDispositivos"
@enduml
