@startuml

class AppGestionDispositivos {
    + main(String[] args)
}

abstract class Dispositivo {
    - String nombre
    - boolean estado
    # Dispositivo(String nombre)
    # encender()
    + apagar()
    + mostrarEstado()
}

interface ControlRemoto {
    +sincronizar()
}

class Televisor extends Dispositivo implements ControlRemoto {
    + encender()
    + sincronizar()
}

class ParlanteInteligente extends Dispositivo {
    + encender()
}

class AireAcondicionado extends Dispositivo implements ControlRemoto {
    + encender()
    + sincronizar()
}

AppGestionDispositivos ..> Dispositivo : "listaDispositivos"
Dispositivo <|-[hidden]- Televisor
Dispositivo <|-[hidden]- ParlanteInteligente
Dispositivo <|-[hidden]- AireAcondicionado

ControlRemoto -[hidden]-> Televisor
ControlRemoto -[hidden]-> AireAcondicionado

@enduml
